import json


def build_notification_payload(event: dict) -> dict:
    """
    Build a sanitized executive notification payload.

    NOTE:
    The private SAMSON implementation includes:
    - Amazon SNS delivery
    - threshold-based notification logic
    - executive summary formatting
    - severity-aware alert routing
    - governance approval context
    - leadership notification workflows

    This public version preserves the notification contract
    while protecting proprietary alerting logic.
    """

    severity = event.get("severity", "UNKNOWN")

    message = {
        "project": "SAMSON",
        "severity": severity,
        "risk_score": event.get("risk_score", "sanitized"),
        "event_name": event.get("event_name", "sanitized-governance-event"),
        "approval_status": event.get("approval_status", "REVIEW_REQUIRED"),
        "executive_summary": event.get(
            "executive_summary",
            "Executive governance summary generated by SAMSON.",
        ),
    }

    return {
        "subject": f"SAMSON Alert: {severity} Governance Event",
        "message": json.dumps(message, indent=2),
    }


def should_notify(event: dict) -> bool:
    """
    Public showcase notification decision.

    The private implementation applies configurable thresholds,
    severity rules, and governance routing criteria.
    """

    return event.get("severity", "LOW") in ["HIGH", "CRITICAL"]


def publish_notification(event: dict) -> dict:
    """
    Public showcase notification publisher.

    No external notification is sent from this sanitized version.
    """

    payload = build_notification_payload(event)

    return {
        "notification_sent": False,
        "reason": "public_showcase_mode",
        "payload": payload,
    }